AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - '**/Gemfile'

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/StringLiterals:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/FileName:
  Enabled: false

Style/AsciiComments:
  Enabled: false
